spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/modernstores;AUTO_SERVER=true
    #url: jdbc:h2:mem:demodb
    username: sa
    password: pwd
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console    
